/* Profile data Storing table */
CREATE TABLE PROFILE_LOGIN_DATA(
ACCOUNT_ID VARCHAR(255) PRIMARY KEY,
USER_NAME VARCHAR(255) UNIQUE NOT NULL,
USER_EMAIL VARCHAR(255) UNIQUE NOT NULL,
USER_PASS VARCHAR(255) NOT NULL,
USER_CREATE_DATE TIMESTAMP,
USER_LAST_LOGIN TIMESTAMP on Update CURRENT_TIMESTAMP
);

CREATE TABLE TRAVIAN_SERVERS(
SRVRID VARCHAR (25) PRIMARY KEY,
SRVRURL VARCHAR (250) NOT NULL,
SRVRVER VARCHAR (10) NOT NULL,
SRVRCNTRY VARCHAR (10) NOT NULL,
SRVRSTATUS VARCHAR (10) NOT NULL,
SRVRSRTDATE VARCHAR (10) NOT NULL
);

/* Player - server details */
CREATE TABLE PLAYER_SERVER(
	ACCOUNT_ID VARCHAR(255) NOT NULL,
	USER_NM VARCHAR(255) NOT NULL,	
	SERVER_ID VARCHAR(255) NOT NULL,
	LDR_STS BOOLEAN DEFAULT FALSE,
	DEF_STS BOOLEAN DEFAULT FALSE,
	OFF_STS BOOLEAN DEFAULT FALSE,
	ART_STS BOOLEAN DEFAULT FALSE,
	STATUS_DT TIMESTAMP,
	FOREIGN KEY (ACCOUNT_ID) REFERENCES PROFILE_LOGIN_DATA (ACCOUNT_ID),
	FOREIGN KEY (SERVER_ID) REFERENCES PROFILE_LOGIN_DATA (SRVRID)
);

/*Storing the list of the map details related to different servers*/
CREATE TABLE MAPS_TABLE_LIST(
TABLEID VARCHAR(25) PRIMARY KEY,
SRVRINST VARCHAR (10) NOT NULL,
SRVRCNTRY VARCHAR (10) NOT NULL,
TBLNM VARCHAR(20) NOT NULL,
SRVRUPDDT TIMESTAMP,
MAP_STATUS VARCHAR(50)
);

/* Basic Table creating table*/
CREATE TABLE MAPS(
WORLDID INT(11),
X INT(11),
Y INT(11),
ID INT(11),
VID INT(11),
VILLAGE VARCHAR(50),
UID INT(11),
PLAYER VARCHAR(50),
AID INT(11),
ALLIANCE VARCHAR(50),
POPULATION INT(11),
TABLEID VARCHAR(20),
UPDATETIME VARCHAR(25)
);


/*Diff Maps table*/
CREATE TABLE diff_maps(
WorldId INT(11) PRIMARY KEY,
x INT(11),
y INT(11),
id INT(11),
vid INT(11),
village VARCHAR(50),
uid INT(11),
player VARCHAR(50),
aid INT(11),
alliance VARCHAR(50),
population INT(11),
diff_5days INT(11),
Status VARCHAR(50)
);


